// Paper theme adapted from Mermaid 12 Neutral (MIT). Shared by SSR and editor previews.
const latin =
  '"Times New Roman", Times, "Nimbus Roman No9 L", "Liberation Serif", "DejaVu Serif", Georgia';
const font =
  latin +
  ' , "Yu Mincho", "YuMincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif JP", "Noto Serif CJK JP", serif';
const emphasisFont =
  latin +
  ', "Hiragino Sans", "Hiragino Kaku Gothic ProN", "Yu Gothic", "YuGothic", "Noto Sans JP", "Noto Sans CJK JP", sans-serif';
const paper = "#f2ead5",
  ink = "#352f25",
  line = "#8c7763",
  red = "#87594f";
const palette = [
  "#c3a28f",
  "#b1b798",
  "#9dafa9",
  "#b0a0b1",
  "#c6b27d",
  "#9aabc0",
  "#c8a2a0",
  "#aea38a",
  "#a7b9b2",
  "#c4b4c8",
  "#d1be98",
  "#a4a0b5",
];
// Official Mermaid 12.0.0 Neutral theme, exported from the bundled runtime. MIT.
const neutralTheme = {
  primaryColor: "#eee",
  contrast: "#707070",
  secondaryColor: "hsl(0, 0%, 98.9215686275%)",
  background: "#ffffff",
  tertiaryColor: "hsl(-160, 0%, 93.3333333333%)",
  primaryBorderColor: "hsl(0, 0%, 83.3333333333%)",
  secondaryBorderColor: "hsl(0, 0%, 88.9215686275%)",
  tertiaryBorderColor: "hsl(-160, 0%, 83.3333333333%)",
  primaryTextColor: "#111111",
  secondaryTextColor: "rgb(2.7499999999, 2.7499999999, 2.7499999999)",
  tertiaryTextColor: "rgb(17.0000000001, 17.0000000001, 17.0000000001)",
  lineColor: "#666",
  textColor: "#000000",
  mainBkg: "#eee",
  secondBkg: "hsl(0, 0%, 98.9215686275%)",
  border1: "#999",
  border2: "#707070",
  note: "#ffa",
  text: "#333",
  critical: "#d42",
  done: "#bbb",
  arrowheadColor: "#333333",
  fontFamily: '"trebuchet ms", verdana, arial, sans-serif',
  fontSize: "16px",
  THEME_COLOR_LIMIT: 12,
  radius: 5,
  strokeWidth: 1,
  nodeBkg: "#eee",
  nodeBorder: "#999",
  clusterBkg: "hsl(0, 0%, 98.9215686275%)",
  clusterBorder: "#707070",
  defaultLinkColor: "#666",
  titleColor: "#333",
  edgeLabelBackground: "white",
  actorBorder: "hsl(0, 0%, 83%)",
  actorBkg: "#eee",
  actorTextColor: "#333",
  actorLineColor: "hsl(0, 0%, 83%)",
  signalColor: "#333",
  signalTextColor: "#333",
  labelBoxBkgColor: "#eee",
  labelBoxBorderColor: "hsl(0, 0%, 83%)",
  labelTextColor: "#333",
  loopTextColor: "#333",
  noteBorderColor: "#999",
  noteBkgColor: "#666",
  noteTextColor: "#fff",
  activationBorderColor: "#666",
  activationBkgColor: "#f4f4f4",
  sequenceNumberColor: "white",
  sectionBkgColor: "hsl(0, 0%, 73.9215686275%)",
  altSectionBkgColor: "white",
  sectionBkgColor2: "hsl(0, 0%, 73.9215686275%)",
  excludeBkgColor: "#eeeeee",
  taskBorderColor: "hsl(0, 0%, 33.9215686275%)",
  taskBkgColor: "#707070",
  taskTextLightColor: "white",
  taskTextColor: "white",
  taskTextDarkColor: "#333",
  taskTextOutsideColor: "#333",
  taskTextClickableColor: "#003163",
  activeTaskBorderColor: "hsl(0, 0%, 33.9215686275%)",
  activeTaskBkgColor: "#eee",
  gridColor: "hsl(0, 0%, 90%)",
  doneTaskBkgColor: "#bbb",
  doneTaskBorderColor: "#666",
  critBkgColor: "#d42",
  critBorderColor: "hsl(10.9090909091, 73.3333333333%, 40%)",
  todayLineColor: "#d42",
  vertLineColor: "#d42",
  personBorder: "hsl(0, 0%, 83.3333333333%)",
  personBkg: "#eee",
  archEdgeColor: "#666",
  archEdgeArrowColor: "#666",
  archEdgeWidth: "3",
  archGroupBorderColor: "hsl(0, 0%, 83.3333333333%)",
  archGroupBorderWidth: "2px",
  noteFontWeight: "normal",
  fontWeight: "normal",
  rowOdd: "hsl(0, 0%, 100%)",
  rowEven: "#f4f4f4",
  labelColor: "black",
  errorBkgColor: "#552222",
  errorTextColor: "#552222",
  useGradient: true,
  gradientStart: "hsl(0, 0%, 83.3333333333%)",
  gradientStop: "hsl(0, 0%, 88.9215686275%)",
  dropShadow: "drop-shadow( 1px 2px 2px rgba(185,185,185,1))",
  rectBkgColor: "hsl(-160, 0%, 93.3333333333%)",
  cScale0: "#555",
  cScale1: "#F4F4F4",
  cScale2: "#555",
  cScale3: "#BBB",
  cScale4: "#777",
  cScale5: "#999",
  cScale6: "#DDD",
  cScale7: "#FFF",
  cScale8: "#DDD",
  cScale9: "#BBB",
  cScale10: "#999",
  cScale11: "#777",
  cScaleInv0: "#aaaaaa",
  cScaleInv1: "#0b0b0b",
  cScaleInv2: "#aaaaaa",
  cScaleInv3: "#444444",
  cScaleInv4: "#888888",
  cScaleInv5: "#666666",
  cScaleInv6: "#222222",
  cScaleInv7: "#000000",
  cScaleInv8: "#222222",
  cScaleInv9: "#444444",
  cScaleInv10: "#666666",
  cScaleInv11: "#888888",
  cScalePeer0: "hsl(0, 0%, 23.3333333333%)",
  cScalePeer1: "hsl(0, 0%, 85.6862745098%)",
  cScalePeer2: "hsl(0, 0%, 23.3333333333%)",
  cScalePeer3: "hsl(0, 0%, 63.3333333333%)",
  cScalePeer4: "hsl(0, 0%, 36.6666666667%)",
  cScalePeer5: "hsl(0, 0%, 50%)",
  cScalePeer6: "hsl(0, 0%, 76.6666666667%)",
  cScalePeer7: "hsl(0, 0%, 90%)",
  cScalePeer8: "hsl(0, 0%, 76.6666666667%)",
  cScalePeer9: "hsl(0, 0%, 63.3333333333%)",
  cScalePeer10: "hsl(0, 0%, 50%)",
  cScalePeer11: "hsl(0, 0%, 36.6666666667%)",
  scaleLabelColor: "#333",
  cScaleLabel0: "#F4F4F4",
  cScaleLabel2: "#F4F4F4",
  cScaleLabel1: "#333",
  cScaleLabel3: "#333",
  cScaleLabel4: "#333",
  cScaleLabel5: "#333",
  cScaleLabel6: "#333",
  cScaleLabel7: "#333",
  cScaleLabel8: "#333",
  cScaleLabel9: "#333",
  cScaleLabel10: "#333",
  cScaleLabel11: "#333",
  surface0: "hsl(0, 0%, 88.3333333333%)",
  surfacePeer0: "hsl(0, 0%, 85.3333333333%)",
  surface1: "hsl(0, 0%, 83.3333333333%)",
  surfacePeer1: "hsl(0, 0%, 80.3333333333%)",
  surface2: "hsl(0, 0%, 78.3333333333%)",
  surfacePeer2: "hsl(0, 0%, 75.3333333333%)",
  surface3: "hsl(0, 0%, 73.3333333333%)",
  surfacePeer3: "hsl(0, 0%, 70.3333333333%)",
  surface4: "hsl(0, 0%, 68.3333333333%)",
  surfacePeer4: "hsl(0, 0%, 65.3333333333%)",
  flowContainerStroke: "hsl(0, 0%, 88.9215686275%)",
  transitionColor: "#000",
  transitionLabelColor: "#000000",
  stateLabelColor: "#111111",
  stateBkg: "#eee",
  labelBackgroundColor: "#eee",
  compositeBackground: "#ffffff",
  altBackground: "#f4f4f4",
  compositeTitleBackground: "#eee",
  stateBorder: "#000",
  innerEndBackground: "hsl(0, 0%, 83.3333333333%)",
  specialStateColor: "#222",
  classText: "#111111",
  fillType0: "#eee",
  fillType1: "hsl(0, 0%, 98.9215686275%)",
  fillType2: "hsl(64, 0%, 93.3333333333%)",
  fillType3: "hsl(64, 0%, 98.9215686275%)",
  fillType4: "hsl(-64, 0%, 93.3333333333%)",
  fillType5: "hsl(-64, 0%, 98.9215686275%)",
  fillType6: "hsl(128, 0%, 93.3333333333%)",
  fillType7: "hsl(128, 0%, 98.9215686275%)",
  pie0: "#555",
  pie1: "#F4F4F4",
  pie2: "#555",
  pie3: "#BBB",
  pie4: "#777",
  pie5: "#999",
  pie6: "#DDD",
  pie7: "#FFF",
  pie8: "#DDD",
  pie9: "#BBB",
  pie10: "#999",
  pie11: "#777",
  pie12: "#555",
  pieTitleTextSize: "25px",
  pieTitleTextColor: "#333",
  pieSectionTextSize: "17px",
  pieSectionTextColor: "#000000",
  pieLegendTextSize: "17px",
  pieLegendTextColor: "#333",
  pieStrokeColor: "black",
  pieStrokeWidth: "2px",
  pieOuterStrokeWidth: "2px",
  pieOuterStrokeColor: "black",
  pieOpacity: "0.7",
  venn1: "#555",
  venn2: "#F4F4F4",
  venn3: "#555",
  venn4: "#BBB",
  venn5: "#777",
  venn6: "#999",
  venn7: "#DDD",
  venn8: "#FFF",
  vennTitleTextColor: "#333",
  vennSetTextColor: "#000000",
  cynefin: {
    domainFontSize: 16,
    itemFontSize: 12,
    boundaryColor: "#666",
    boundaryWidth: 2,
    cliffColor: "#8B0000",
    cliffWidth: 4,
    arrowColor: "#666",
    arrowWidth: 2,
    complexBg: "#E8F5E9",
    complicatedBg: "#E3F2FD",
    chaoticBg: "#FBE9E7",
    clearBg: "#FFF8E1",
    confusionBg: "#F3E5F5",
    textColor: "#000000",
    labelColor: "#111111",
  },
  quadrant1Fill: "#eee",
  quadrant2Fill: "#f3f3f3",
  quadrant3Fill: "#f8f8f8",
  quadrant4Fill: "#fdfdfd",
  quadrant1TextFill: "#111111",
  quadrant2TextFill: "#0c0c0c",
  quadrant3TextFill: "#070707",
  quadrant4TextFill: "#020202",
  quadrantPointFill: "hsl(0, 0%, NaN%)",
  quadrantPointTextFill: "#111111",
  quadrantXAxisTextFill: "#111111",
  quadrantYAxisTextFill: "#111111",
  quadrantInternalBorderStrokeFill: "hsl(0, 0%, 83.3333333333%)",
  quadrantExternalBorderStrokeFill: "hsl(0, 0%, 83.3333333333%)",
  quadrantTitleFill: "#111111",
  xyChart: {
    backgroundColor: "#ffffff",
    titleColor: "#111111",
    dataLabelColor: "#111111",
    legendTextColor: "#111111",
    xAxisTitleColor: "#111111",
    xAxisLabelColor: "#111111",
    xAxisTickColor: "#111111",
    xAxisLineColor: "#111111",
    yAxisTitleColor: "#111111",
    yAxisLabelColor: "#111111",
    yAxisTickColor: "#111111",
    yAxisLineColor: "#111111",
    plotColorPalette:
      "#EEE,#6BB8E4,#8ACB88,#C7ACD6,#E8DCC2,#FFB2A8,#FFF380,#7E8D91,#FFD8B1,#FAF3E0",
  },
  radar: {
    axisColor: "#666",
    axisStrokeWidth: 2,
    axisLabelFontSize: 12,
    curveOpacity: 0.5,
    curveStrokeWidth: 2,
    graticuleColor: "#DEDEDE",
    graticuleStrokeWidth: 1,
    graticuleOpacity: 0.3,
    legendBoxSize: 12,
    legendFontSize: 12,
  },
  wardleyEvolutionColor: "#dc3545",
  wardley: {
    backgroundColor: "#ffffff",
    axisColor: "#666",
    axisTextColor: "#111111",
    gridColor: "hsl(0, 0%, 90%)",
    componentFill: "#ffffff",
    componentStroke: "#666",
    componentLabelColor: "#111111",
    linkStroke: "#666",
    evolutionStroke: "#dc3545",
    annotationStroke: "#666",
    annotationTextColor: "#111111",
    annotationFill: "#ffffff",
  },
  requirementBackground: "#eee",
  requirementBorderColor: "hsl(0, 0%, 83.3333333333%)",
  requirementBorderSize: "1",
  requirementTextColor: "#111111",
  relationColor: "#666",
  relationLabelBackground: "white",
  relationLabelColor: "#333",
  git0: "hsl(0, 0%, 70.6862745098%)",
  git1: "#555",
  git2: "#BBB",
  git3: "#777",
  git4: "#999",
  git5: "#DDD",
  git6: "#FFF",
  git7: "#DDD",
  gitInv0: "rgb(74.75, 74.75, 74.75)",
  gitInv1: "#aaaaaa",
  gitInv2: "#444444",
  gitInv3: "#888888",
  gitInv4: "#666666",
  gitInv5: "#222222",
  gitInv6: "#000000",
  gitInv7: "#222222",
  branchLabelColor: "#333",
  gitBranchLabel0: "#333",
  gitBranchLabel1: "white",
  gitBranchLabel2: "#333",
  gitBranchLabel3: "white",
  gitBranchLabel4: "#333",
  gitBranchLabel5: "#333",
  gitBranchLabel6: "#333",
  gitBranchLabel7: "#333",
  tagLabelColor: "#111111",
  tagLabelBackground: "#eee",
  tagLabelBorder: "hsl(0, 0%, 83.3333333333%)",
  tagLabelFontSize: "10px",
  commitLabelColor: "rgb(2.7499999999, 2.7499999999, 2.7499999999)",
  commitLabelBackground: "hsl(0, 0%, 98.9215686275%)",
  commitLabelFontSize: "10px",
  emUiFill: "white",
  emUiStroke: "#dbdada",
  emProcessorFill: "#edb3f6",
  emProcessorStroke: "#b88cbf",
  emReadModelFill: "#d3f1a2",
  emReadModelStroke: "#a3b732",
  emCommandFill: "#bcd6fe",
  emCommandStroke: "#679ac3",
  emEventFill: "#ffb778",
  emEventStroke: "#c19a0f",
  emSwimlaneBackgroundOdd: "rgb(250,250,250)",
  emSwimlaneBackgroundStroke: "rgb(240,240,240)",
  emArrowhead: "#666",
  emRelationStroke: "#666",
  attributeBackgroundColorOdd: "#ffffff",
  attributeBackgroundColorEven: "#f2f2f2",
};
function makeConfig(size) {
  const v = {
    background: paper,
    fontFamily: font,
    fontSize: size + "px",
    primaryColor: "#eee4ce",
    primaryTextColor: ink,
    primaryBorderColor: line,
    secondaryColor: "#e9dfc7",
    secondaryTextColor: ink,
    secondaryBorderColor: line,
    tertiaryColor: "#e5d2c3",
    tertiaryTextColor: ink,
    tertiaryBorderColor: line,
    lineColor: "#796452",
    textColor: ink,
    mainBkg: "#eee4ce",
    nodeBkg: "#eee4ce",
    nodeTextColor: ink,
    nodeBorder: line,
    clusterBkg: "#ede3cd",
    clusterBorder: line,
    edgeLabelBackground: paper,
    defaultLinkColor: line,
    titleColor: ink,
    arrowheadColor: line,
    flowContainerStroke: line,
    radius: 0,
    useGradient: false,
    dropShadow: "none",
    actorBkg: "#eee4ce",
    actorBorder: line,
    actorTextColor: ink,
    actorLineColor: line,
    signalColor: "#796452",
    signalTextColor: ink,
    labelBoxBkgColor: "#e9dfc7",
    labelBoxBorderColor: line,
    labelTextColor: ink,
    loopTextColor: ink,
    noteBkgColor: "#e9dfc7",
    noteBorderColor: line,
    noteTextColor: ink,
    activationBkgColor: "#d8c5aa",
    activationBorderColor: line,
    sequenceNumberColor: paper,
    personBkg: "#e9dfc7",
    personBorder: line,
    classText: ink,
    attributeBackgroundColorOdd: "#eee4ce",
    attributeBackgroundColorEven: "#e9dfc7",
    rowOdd: "#eee4ce",
    rowEven: "#e9dfc7",
    transitionColor: line,
    transitionLabelColor: ink,
    stateLabelColor: ink,
    stateBkg: "#eee4ce",
    labelBackgroundColor: paper,
    compositeBackground: "#eee4ce",
    altBackground: "#e9dfc7",
    compositeTitleBackground: "#e9dfc7",
    compositeBorder: line,
    innerEndBackground: line,
    specialStateColor: line,
    errorBkgColor: "#e5d2c3",
    errorTextColor: ink,
    scaleLabelColor: ink,
    sectionBkgColor: "#e9dfc7",
    altSectionBkgColor: paper,
    sectionBkgColor2: "#e4dcc9",
    excludeBkgColor: "#ded5c1",
    taskBorderColor: line,
    taskBkgColor: palette[0],
    activeTaskBorderColor: red,
    activeTaskBkgColor: palette[1],
    doneTaskBkgColor: "#c6c0ad",
    doneTaskBorderColor: line,
    critBorderColor: red,
    critBkgColor: "#c8a2a0",
    todayLineColor: red,
    vertLineColor: line,
    gridColor: "#c4b59e",
    taskTextColor: ink,
    taskTextOutsideColor: ink,
    taskTextLightColor: ink,
    taskTextDarkColor: ink,
    taskTextClickableColor: red,
    requirementBackground: "#eee4ce",
    requirementBorderColor: line,
    requirementTextColor: ink,
    relationColor: line,
    relationLabelBackground: paper,
    relationLabelColor: ink,
    archEdgeColor: line,
    archEdgeArrowColor: line,
    archGroupBorderColor: line,
    pieTitleTextColor: ink,
    pieSectionTextColor: ink,
    pieLegendTextColor: ink,
    pieStrokeColor: paper,
    pieOuterStrokeColor: line,
    pieOpacity: 1,
    pieTitleTextSize: size * 1.2 + "px",
    pieSectionTextSize: size + "px",
    pieLegendTextSize: size + "px",
    vennTitleTextColor: ink,
    vennSetTextColor: ink,
    branchLabelColor: ink,
    tagLabelColor: ink,
    tagLabelBackground: "#e9dfc7",
    tagLabelBorder: line,
    tagLabelFontSize: size * 0.85 + "px",
    commitLabelColor: ink,
    commitLabelBackground: paper,
    commitLabelFontSize: size * 0.85 + "px",
    emUiFill: "#e9dfc7",
    emUiStroke: line,
    emProcessorFill: palette[3],
    emProcessorStroke: line,
    emReadModelFill: palette[2],
    emReadModelStroke: line,
    emCommandFill: palette[1],
    emCommandStroke: line,
    emEventFill: palette[0],
    emEventStroke: line,
    emSwimlaneBackgroundOdd: "#e9dfc7",
    emSwimlaneBackgroundStroke: line,
    emArrowhead: line,
    emRelationStroke: line,
  };
  palette.forEach((c, i) => {
    v["cScale" + i] = c;
    v["cScaleLabel" + i] = ink;
    v["cScaleInv" + i] = ink;
    v["pie" + (i + 1)] = c;
    if (i < 8) {
      v["git" + i] = c;
      v["gitInv" + i] = ink;
      v["gitBranchLabel" + i] = ink;
      v["fillType" + i] = c;
      v["actor" + i] = c;
      v["venn" + (i + 1)] = c;
    }
  });
  for (let n = 1; n <= 4; n++) {
    v["quadrant" + n + "Fill"] = ["#e5d2c3", "#e1dfcb", "#eee4ce", "#d9dfd6"][n - 1];
    v["quadrant" + n + "TextFill"] = ink;
  }
  for (const k of ["Point", "PointText", "XAxisText", "YAxisText", "Title"])
    v["quadrant" + k + "Fill"] = ink;
  v.quadrantInternalBorderStrokeFill = line;
  v.quadrantExternalBorderStrokeFill = line;
  v.xyChart = {
    backgroundColor: paper,
    titleColor: ink,
    dataLabelColor: ink,
    legendTextColor: ink,
    plotColorPalette: [palette[0], "#506f45", "#496b8a", "#87594f", ...palette.slice(4)].join(","),
  };
  for (const axis of ["x", "y"])
    for (const key of ["Title", "Label", "Tick", "Line"])
      v.xyChart[axis + "Axis" + key + "Color"] = ink;
  v.radar = {
    axisColor: line,
    axisLabelFontSize: size,
    legendFontSize: size,
    graticuleColor: line,
    graticuleOpacity: 0.35,
    curveOpacity: 0.22,
  };
  v.cynefin = {
    complexBg: "#d9dfd6",
    complicatedBg: "#e1dfcb",
    chaoticBg: "#e5d2c3",
    clearBg: "#eee4ce",
    confusionBg: "#ded5df",
    boundaryColor: line,
    cliffColor: red,
    arrowColor: line,
    textColor: ink,
    labelColor: ink,
    domainFontSize: size,
    itemFontSize: size * 0.8,
  };
  v.wardley = {
    backgroundColor: paper,
    axisColor: line,
    axisTextColor: ink,
    gridColor: "#c4b59e",
    componentFill: paper,
    componentStroke: line,
    componentLabelColor: ink,
    linkStroke: line,
    evolutionStroke: red,
    annotationStroke: line,
    annotationTextColor: ink,
    annotationFill: paper,
  };
  const c = {
    startOnLoad: false,
    securityLevel: "strict",
    suppressErrorRendering: true,
    theme: "base",
    look: "classic",
    layout: "dagre",
    fontFamily: font,
    fontSize: size,
    htmlLabels: false,
    themeVariables: { ...neutralTheme, ...v },
    flowchart: {
      htmlLabels: false,
      curve: "linear",
      padding: 10,
      nodeSpacing: 24,
      rankSpacing: 30,
      minNodeWidth: 0,
      wrappingWidth: 180,
      subGraphTitleMargin: { top: 6, bottom: 10 },
    },
    sequence: {
      actorFontSize: size,
      noteFontSize: size,
      messageFontSize: size,
      actorFontFamily: font,
      noteFontFamily: font,
      messageFontFamily: font,
      mirrorActors: false,
      actorMargin: 32,
      width: 112,
      height: 42,
      boxMargin: 12,
      messageMargin: 34,
    },
    gantt: {
      fontSize: size * 0.85,
      sectionFontSize: size * 0.85,
      barHeight: size * 1.6,
      barGap: 8,
    },
    journey: {
      taskFontSize: size,
      taskFontFamily: font,
      titleFontFamily: font,
      titleFontSize: size * 1.2 + "px",
      actorColours: palette,
      sectionFills: palette,
      sectionColours: [ink],
    },
    quadrantChart: {
      titleFontSize: size * 1.2,
      xAxisLabelFontSize: size,
      yAxisLabelFontSize: size,
      quadrantLabelFontSize: size,
      pointLabelFontSize: size * 0.85,
      pointTextPadding: 14,
      quadrantTextTopPadding: 12,
    },
    xyChart: {
      titleFontSize: size * 1.2,
      legendFontSize: size,
      xAxis: { labelFontSize: size, titleFontSize: size },
      yAxis: { labelFontSize: size, titleFontSize: size },
    },
    architecture: { fontSize: size },
    treemap: { labelFontSize: size, valueFontSize: size * 0.85 },
    packet: { bitWidth: 24, rowHeight: size * 2 },
    c4: {
      width: 156,
      height: 44,
      c4ShapeMargin: 34,
      c4ShapePadding: 12,
      diagramMarginX: 48,
      diagramMarginY: 12,
      c4ShapeInRow: 3,
      c4BoundaryInRow: 2,
    },
  };
  c.state = { minNodeWidth: 0, wrappingWidth: 180 };
  c.class = { nodeSpacing: 28, rankSpacing: 32 };
  c.er = { entityPadding: 12, nodeSpacing: 28, rankSpacing: 36 };
  c.usecase = { nodeSpacing: 28, rankSpacing: 38 };
  c.agentflow = { nodeSpacing: 24, rankSpacing: 32 };
  c.journey = {
    ...c.journey,
    width: 112,
    height: 40,
    taskMargin: 28,
    diagramMarginX: 12,
    diagramMarginY: 8,
  };
  c.timeline = { padding: 16, diagramMarginX: 12, diagramMarginY: 8 };
  c.architecture = { ...c.architecture, padding: 20, iconSize: 56, nodeSeparation: 40 };
  const kinds = [
    "person",
    "external_person",
    "system",
    "external_system",
    "system_db",
    "external_system_db",
    "system_queue",
    "external_system_queue",
    "container",
    "external_container",
    "container_db",
    "external_container_db",
    "container_queue",
    "external_container_queue",
    "component",
    "external_component",
    "component_db",
    "external_component_db",
    "component_queue",
    "external_component_queue",
    "boundary",
    "message",
  ];
  for (const k of kinds) {
    c.c4[k + "FontSize"] = size;
    c.c4[k + "FontFamily"] = font;
    c.c4[k + "_bg_color"] = k.startsWith("external") ? "#e9dfc7" : "#eee4ce";
    c.c4[k + "_border_color"] = line;
  }
  c.railroad = {
    fontFamily: font,
    fontSize: size,
    terminalFill: "#e9dfc7",
    terminalStroke: line,
    terminalTextColor: ink,
    nonTerminalFill: "#eee4ce",
    nonTerminalStroke: line,
    nonTerminalTextColor: ink,
    lineColor: line,
    markerFill: line,
    commentFill: paper,
    commentStroke: line,
    commentTextColor: ink,
    specialFill: "#e5d2c3",
    specialStroke: red,
    ruleNameColor: ink,
  };
  c.themeCSS = `text { font-family: ${font}; }
 tspan { font-family:inherit; }
 strong, b, .c4-shape .label .c4-name, .classTitle,
 [font-weight="bold"], [font-weight="600"], [font-weight="700"],
 [style*="font-weight: bold"], [style*="font-weight:bold"],
 [style*="font-weight: 600"], [style*="font-weight:600"],
 [style*="font-weight: 700"], [style*="font-weight:700"] {
   font-family:${emphasisFont}!important;font-weight:600!important;letter-spacing:normal;
 }

 .nodeLabel p { text-align:center; text-align-last:center; margin:0; }
 .c4-shape .label, .c4-shape .label text, .c4-shape .label tspan { color:${ink}!important;fill:${ink}!important; }
 .packetBlock {fill:#eee4ce;stroke:${line};} .packetLabel,.packetByte.start,.packetByte.end,.packetTitle {fill:${ink};}
 .treeView-node-label,.treeView-node-dir {fill:${ink};} .treeView-highlight-bg {fill:#e5d2c3;stroke:#87594f;rx:0;} .treeView-connector {stroke:${line};}
 .face {fill:#e9dfc7;stroke:${line};} .mouth {stroke:${line};}
 .radarCurve-0,.radarLegendBox-0 {stroke:#87594f;stroke-width:2;}
 .radarCurve-1,.radarLegendBox-1 {stroke:#506f45;stroke-width:2;stroke-dasharray:6 3;}
 .railroad-terminal rect {fill:#e9dfc7;stroke:${line};}
 [style*="#087ebf"] {fill:${line}!important;}
 `;
  return c;
}

/** @type {import("mermaid").MermaidConfig} */
export const MERMAID_CONFIG = makeConfig(16);
